matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      dist: xenial
      language: python  
      python:
        - "3.5"
      services:
        - xvfb
    - os: linux
      dist: xenial
      language: python  
      python:
        - "3.6"
      services:
        - xvfb
    - os: linux
      dist: xenial
      language: python  
      python:
        - "3.7"
      services:
        - xvfb


# osx deps
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite freetype; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libpng; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-darwin-amd64-1.2.0.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar -zxvf git-lfs-darwin-amd64-1.2.0.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=`pwd`/git-lfs-1.2.0:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "https://${GH_TOKEN}@github.com" > .git/credentials; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git config credential.helper "store --file=.git/credentials"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git remote set-url origin https://github.com/PlutoVR/lfs-test.git; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p $HOME/bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PATH:$HOME/bin/; fi



install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran libfreetype6-dev libpng-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install subversion; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install svn; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install --upgrade numpy; fi
  - pip3 install --upgrade cython
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install --upgrade pywavelets; fi
  - python3 setup.py install
  - pip3 install codecov
  #- pip3 install --upgrade --force-reinstall pyqt5
  - pip3 install --force-reinstall pyqt5==5.11.3
  - pip3 install --force-reinstall PyQt5-sip==4.19.13
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/populse/populse_db.git
  - cd populse_db
  - pip3 install -e .[postgres]
  - pip3 install --force-reinstall lark-parser==0.6.7
  - cd ..
  #- git clone --depth=50 --branch=master https://github.com/populse/soma-base.git
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 uninstall --yes soma-base; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 uninstall --yes soma-base; fi
  #- git clone --depth=50 --branch=master https://github.com/populse/capsul.git
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 uninstall --yes capsul; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 uninstall --yes capsul; fi
  #- cd capsul
  #- python setup.py install
  #- cd ..
  - cd populse_mia
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PYTHONPATH="$PYTHONPATH:/home/travis/build/populse/populse_mia/python"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYTHONPATH="$PYTHONPATH:/Users/travis/build/populse/populse_mia/python"; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PYTHONPATH="$PYTHONPATH:/home/travis/build/populse/soma-base/python"; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYTHONPATH="$PYTHONPATH:/Users/travis/build/populse/soma-base/python"; fi

  - "export DISPLAY=:99.0"
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start

script:
  - python3 -V
  - python3 ./python/populse_mia/test.py -v
  - coverage run ./python/populse_mia/test.py

after_success:
- codecov
